### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by e3dio** [uNetworking/uWebSockets.js#918] opened 2023-06-02 15:58 UTC
If you get an error like `Error: Returning from a request handler without responding or attaching an abort handler is forbidden!` that is fine can fix it, but it also prints `terminate called without an active exception` then cpu goes to 100% for process `systemd-coredum` and the node process won't exit with ctr+c for like 10 seconds then `Aborted (core dumped)`, it should just immediately exit the program

**Comment by e3dio** [comment] 2023-06-07 16:35
Wasn't there discussion about default behavior to set `res.onAborted(() => res.aborted = true)` if callback returns without ending response, 99% of time that is all you need and check abort status when async returns. It saves line of code and removes need to declare function in hot path, not sure how that affects perf. Optionally set res.onAborted() if want to add more than `res.aborted = true`

**Comment by uNetworkingAB** [comment] 2023-12-24 04:47
I think this not not a bug but just your coredump taking a long time? We call std::terminate on invalid use, and this calls std::abort which causes a coredump on some systems. I think this is fine, because calling std::exit would be just a normal program termination. IMO there is nothing to fix here, so closing for now.

**Closed by uNetworkingAB** 2023-12-24 04:47 UTC
