### ISSUE TITLE
Segmentation fault if files required for SSL do not exist

### ISSUE THREAD

**Issue by mrlika** [uNetworking/uWebSockets.js#71] opened 2019-02-22 10:52 UTC
If the files from SSLApp setting do not exist in file system
```json
{
    "key_file_name": "misc/key.pem",
    "cert_file_name": "misc/cert.pem",
    "dh_params_file_name": "misc/params.dh"
}
```
segmentation fault happens

```
uWebSockets.SSLApp(this.settings);
                          ^
App construction failed
Segmentation fault (core dumped)
```

**Comment by alexhultman** [comment] 2019-02-22 13:36
I believe this is really more like #66. It exits because you did not catch the thrown exception

**Comment by alexhultman** [comment] 2019-02-27 16:46
Closing this as a duplicate of 66

**Closed by alexhultman** 2019-02-27 16:46 UTC

**Comment by alexhultman** [comment] 2019-03-02 03:45
This should be fixed now
