### ISSUE TITLE
v18 missing typing

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#321] opened 2020-06-05 17:03 UTC
Really nice update! but have you planned to do the typings too? do you want help or are you just waiting the update with the new Websocket type?

**Comment by alexhultman** [comment] 2020-06-07 08:28
https://github.com/uNetworking/uWebSockets.js/pull/312

They will be updated for the purpose of documentation, but I don't know what to do with the PR yet

**Comment by yovanoc** [comment] 2020-06-07 08:38
Yes but there isn't the typing for the new upgrade thing etc.

My opinion for this PR is what I said, force the user to pass an objet like to merge with the other websocket fields, or let it put a number or whatever and make a breaking change to only allow retrieving data with getUserData()

**Comment by alexhultman** [comment] 2020-06-07 09:29
Yes, UserData is an object, but that's not the issue. The issue is that JavaScript does not have types, so even if TypeScript adds types, there's no way for V8 to properly call the default constructor of that UserData type. Types are lost once compiled to JS and we only deal with JS, so it fails.

If V8 could run TypeScript it would be a whole different thing, but that's not how it works. TypeScript compiler removes all that type info.

**Comment by alexhultman** [comment] 2020-06-07 09:33
If I do app.ws<UserData>(...) in C++, we can internally call the default constructor of UserData because we know its type and therefore the constructor to call. So users get what they expect; a properly initialized UserData object.

If I do app.ws<UserData>(..) in TypeScript, this templated function call compiles down to a regular non-templated app.ws function call without any type info. So the actual native code does not know where the default constructor is, it just becomes an empty Object.

**Comment by alexhultman** [comment] 2020-06-07 09:37
How do you even represent "type" in JavaScript? A reference to its prototype?

Does TypeScript hand the prototype of that type to the function as first argument? How does TypeScript compile this? I need to know the prototype of UserData.

**Comment by alexhultman-2fa** [comment] 2020-06-07 10:09
Is it possible to mark UserData as something that doesn't have a default constructor?

**Comment by alexhultman-2fa** [comment] 2020-06-07 14:31
TypeScript **interfaces** do not define any initialization or constructor while **classes** do. So taking UserData as an interface could work.

**Comment by alexhultman** [comment] 2020-06-08 14:06
There are updated typed and docs in v18.1 now

**Comment by yovanoc** [comment] 2020-06-08 14:09
Oh very nice! but https://github.com/uNetworking/uWebSockets.js/blob/b0af297f26727696fac290bf79e0d5f88f401271/docs/index.d.ts#L197 should remove the httprequest here no?

**Comment by alexhultman** [comment] 2020-06-08 14:13
Yes I missed that 🤦

**Comment by alexhultman** [comment] 2020-06-20 21:24
That should be fixed in newest docs now and will be updated in next release.

**Closed by alexhultman** 2020-06-20 21:24 UTC
Labels: documentation, enhancement
