### ISSUE TITLE
Error: Module did not self-register (Node 21.5.0 and uWS 20.35.0)

### ISSUE THREAD

**Issue by aleksraiden** [uNetworking/uWebSockets.js#999] opened 2023-12-21 08:36 UTC
Hi all, try to use both latest version of NodeJS and uWS, But we have an error:
`
Error: Module did not self-register: '/builds/devs/uws/uws_linux_x64_120.node'.
    at /builds/devs/uws/uws.js:22:9
    at Object.<anonymous>
    at Module._compile (node:internal/modules/cjs/loader:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:1[76])
    at Object.<anonymous> (/builds/devs/adminApiGateway.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
Node.js v21.5.0
`
Of course, all binaries available, we check signature - in latest nodejs still usage version 120. 
In pervious, 21.4.0 nodejs - all OK.

**Comment by uNetworkingAB** [comment] 2023-12-21 08:40
You probably aren't using official Node.js builds download from nodejs.org

**Comment by ardatan** [comment] 2023-12-22 10:33
Same here;
https://github.com/ardatan/feTS/actions/runs/7292079034/job/19872333146?pr=974

**Comment by andrey-dubnik** [comment] 2023-12-22 11:02
It does look like the problem is 20.35.0 release specific, setting 20.34.0 explicitly sorted the issue in our case...

**Comment by uNetworkingAB** [comment] 2023-12-23 01:38
Last release is broken from a linker issue. Will be fixed in next

**Comment by uNetworkingAB** [comment] 2023-12-23 01:42
CI is building a fix that works, will release when done

**Closed** 2023-12-23 03:41 UTC
Labels: bug
