### ISSUE TITLE
Graceful shutdown + worker threads crashes node process 

### ISSUE THREAD

**Issue by SkeLLLa** [uNetworking/uWebSockets.js#324] opened 2020-06-13 12:05 UTC
Hi, thanks for awesome lib.

I've tried to play around with worker threads example combined with graceful shutdown. And find out that it crashes process on exit.

Config:
* Linux kernel 5.6.X
* uWebSockets.js 18.1.0
* Node 14.3.0

Here's code that's mostly taken from examples dir.

```js
const uWS = require('uWebSockets.js');
const { Worker, isMainThread, threadId, parentPort } = require('worker_threads');
const os = require('os');

const port = 9001;

if (isMainThread) {
    const workers = os.cpus().map(() => {
        return new Worker(__filename);
    });
    const cleanup = function cleanup() {
        workers.forEach((worker) => {
            worker.postMessage('cleanup');
        });
    };
    process.on('SIGTERM', cleanup);
    process.on('SIGINT', cleanup);
} else {
    let listenSocket;

    const app = uWS.App({}).listen(port, (token) => {
        listenSocket = token;
        if (token) {
            console.info(`${threadId} listening on ${port}`);
        } else {
            console.error(`${threadId} failed listening on ${port}`);
        }
    });

    parentPort.on('message', (value) => {
        if (value === 'cleanup') {
            shutdown();
            process.exit(0);
        }
    });

    function shutdown() {
        if (listenSocket) {
            uWS.us_listen_socket_close(listenSocket);
            listenSocket = null;
        }
    }
}
```

It launches without any errors, all threads listening. But when you send `SIGINT` for example node crashes with following core dump:

```
uv loop at [0x7f40b93f7ad8] has open handles:
[0x7f40940b9b10] prepare (active)
        Close callback: (nil) 
        Data: 0x7f40940c1ad0 
        (First field): 0x7f40940de240 
[0x7f40940b9b90] check (active)
        Close callback: (nil) 
        Data: 0x7f40940c1ad0 
        (First field): 0x7f40940de240 
[0x7f40940de300] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f40940de240 
        (First field): 0x7f40940cce40 
[0x7f40940f14e0] async (active)
        Close callback: 0x1 
        Data: 0x7f40940f1420 
uv loop at [0x7f40b93f7ad8] has 4 open handles in total
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
uv loop at [0x7f408bbfdad8] has open handles:
[0x7f407c0bf030] prepare (active)
        Close callback: (nil) 
        Data: 0x7f407c0c1b20 
        (First field): 0x7f407c0ba740 
[0x7f407c0bf0b0] check (active)
        Close callback: (nil) 
        Data: 0x7f407c0c1b20 
        (First field): 0x7f407c0ba740 
[0x7f407c0ba800] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f407c0ba740 
uv loop at [0x7f408b3fbad8] has open handles:
[0x7f40740bb850] prepare (active)
        Close callback: (nil) 
        Data: 0x7f40740a2950 
        (First field): 0x7f40740c6eb0 
[0x7f40740cb470] check (active)
        Close callback: (nil) 
        Data: 0x7f40740a2950 
        (First field): 0x7f40740c6eb0 
[0x7f40740c6f70] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f40740c6eb0 
[0x7f407c0c9ff0] async (active)
[0x7f40740d2c60] async (active)
        Close callback: 0x7f407c09b601 
        Close callback: 0x7f407409b701 
        Data: 0x7f407c0c9f30 
        Data: 0x7f40740d2ba0 
uv loop at [0x7f408bbfdad8] has 4 open handles in total
uv loop at [0x7f408b3fbad8] has 4 open handles in total
uv loop at [0x7f40b9bf9ad8] has open handles:
[0x7f409c0b9a90] prepare (active)
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
        Close callback: (nil) 
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
        Data: 0x7f409c0c1ff0 
        (First field): 0x7f409c0c5fe0 
[0x7f409c0c0500] check (active)
        Close callback: (nil) 
        Data: 0x7f409c0c1ff0 
        (First field): 0x7f409c0c5fe0 
[0x7f409c0c60a0] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f409c0c5fe0 
[0x7f409c0c9fc0] async (active)
        Close callback: 0x7f409c09b501 
        Data: 0x7f409c0c9f00 
uv loop at [0x7f40b9bf9ad8] has 4 open handles in total
uv loop at [0x7f408bffead8] has open handles:
[0x7f40840ba1f0] prepare (active)
        Close callback: (nil) 
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
        Data: 0x7f40840c1d00 
        (First field): 0x7f40840cc3e0 
[0x7f40840c0430] check (active)
        Close callback: (nil) 
        Data: 0x7f40840c1d00 
        (First field): 0x7f40840cc3e0 
[0x7f40840cc4a0] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f40840cc3e0 
[0x7f40840ce520] async (active)
        Close callback: 0x7f408409b701 
        Data: 0x7f40840ce460 
uv loop at [0x7f408bffead8] has 4 open handles in total
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
uv loop at [0x7f40b97f8ad8] has open handles:
[0x7f40a00c0c70] prepare (active)
        Close callback: (nil) 
        Data: 0x7f40a00c1920 
        (First field): 0x7f40a00bf880 
[0x7f40a00c0cf0] check (active)
        Close callback: (nil) 
        Data: 0x7f40a00c1920 
        (First field): 0x7f40a00bf880 
[0x7f40a00bf940] timer (active)
        Close callback: 0x800000000000000 
        Data: 0x7f40a00bf880 
[0x7f40a00ce710] async (active)
        Close callback: 0x7f40a009b401 
        Data: 0x7f40a00ce650 
uv loop at [0x7f40b97f8ad8] has 4 open handles in total
uv loop at [0x7f40b8bf5ad8] has open handles:
[0x7f408c0b9f50] prepare (active)
node[78601]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
uv loop at [0x7f408affaad8] has open handles:
[0x7f40780d6b70] prepare (active)
        Close callback: (nil) 
 1: 0x558615d2b370 node::Abort() [node]
uv loop at [0x7f40b8ff6ad8] has open handles:
[0x7f40980c4b20] prepare (active)
 1: 0x558615d2b370 node::Abort() [node]
uv loop at [0x7f40b87f4ad8] has open handles:
[0x7f40900b9c30] prepare (active)
 1: 0x558615d2b370 node::Abort() [node]
uv loop at [0x7f40b9ffaad8] has open handles:
[0x7f40a80bfe30] prepare (active)
 1: 0x558615d2b370 node::Abort() [node]
uv loop at [0x7f408b7fcad8] has open handles:
[0x7f40800d67c0] prepare (active)
 1: 0x558615d2b370 node::Abort() [node]
        Close callback: (nil) 
 1: 0x558615d2b370 node::Abort() [node]
        Data: 0x7f408c0c3ba0 
 2: 0x558615d2b3f3  [node]
        Close callback: (nil) 
 2: 0x558615d2b3f3  [node]
        Close callback: (nil) 
 3: 0x558615da74bf  [node]
 4: 0x558615caf908 node::worker::Worker::Run() [node]
 2: 0x558615d2b3f3  [node]
        Close callback: (nil) 
 2: 0x558615d2b3f3  [node]
        Data: 0x7f40780d4460 
 2: 0x558615d2b3f3  [node]
 3: 0x558615da74bf  [node]
 4: 0x558615caf908 node::worker::Worker::Run() [node]
 5: 0x558615cb0125  [node]
 6: 0x7f40c29b9fa7  [/lib64/libpthread.so.0]
 7: 0x7f40c3701dbf clone [/lib64/libc.so.6]
        Data: 0x7f4090077860 
        Close callback: (nil)
```

PS: this also reproduces even if you don't listen anything in workers and just require uws it causes crash when process.exit is called.

```js
const uWS = require('uWebSockets.js'); // comment this and there will be no crash
const { Worker, isMainThread, threadId, parentPort } = require('worker_threads');
const os = require('os');

if (isMainThread) {
    const workers = os.cpus().map(() => {
        return new Worker(__filename);
    });
    const cleanup = function cleanup() {
        workers.forEach((worker) => {
            worker.postMessage('cleanup');
        });
    };
    process.on('SIGTERM', cleanup);
    process.on('SIGINT', cleanup);
    setTimeout(() => {
        process.exit(0);
    }, 5000);
} else {
    parentPort.on('message', (value) => {
        if (value === 'cleanup') {
            process.exit(0);
        }
    });
}
```

Is it expected or am I missing something?

**Comment by hst-m** [comment] 2020-06-13 20:51
I use Cluster for this type of thing and have pretty solid setup including processing SIGTERM events and gracefully shutting down, havent tried worker_thread and wasnt aware it did the same thing as Cluster in handling requests to the same port, I could look into this more

**Comment by hst-m** [comment] 2020-06-13 22:05
I get the same results you do with the process exiting with errors. Not really sure what is going on with that but my recommendation would be to use Cluster for this, [worker_threads ](https://nodejs.org/api/worker_threads.html) are more for spawning tasks to do cpu work? and [Clusters ](https://nodejs.org/api/cluster.html) are for multiple node processes to handle requests. I pasted a simplified/different version of what I use for my main app, should work for you:
```javascript
cluster=require('cluster')
console.log(`starting ${cluster.isMaster?'Master':'Worker '+cluster.worker.id}..`)
if(cluster.isMaster){ // master code
        let shuttingdown,timeout=null
        cluster.on('message',(worker,message,handle)=>{/*processing messages from workers goes here*/console.log('message from worker:',worker.id,message)})
        cluster.on('exit',(worker,code,signal)=>{
                if(!worker.exitedAfterDisconnect)console.log(`Worker${worker.id} died abnormally with ${signal?'signal:'+signal:'code:'+code}`)
                const workers=Object.keys(cluster.workers).length
                if(!shuttingdown&&!workers){console.log('no workers left, starting worker..');clearTimeout(timeout);timeout=setTimeout(()=>cluster.fork(),1000)}
                if(shuttingdown&&!workers){console.log('Master exiting');process.exit(0)}
        })
        const shutdown=sig=>{console.log(`Master ${sig} received, shutting down server..`);shuttingdown=true}
        process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown)
        return require('os').cpus().map(() =>cluster.fork()) // fork some workers
}
// anything below here is worker code
require('uWebSockets.js').App().any('/*',(res,req)=>console.log('request')).listen(3000,()=>console.log('http listening'))
const shutdown=async sig=>{
        console.log(`Worker${cluster.worker.id} received ${sig}, gracefully shutting down..`)
        // code here to gracefully shut down http server and sockets, db connections etc
        console.log(`Worker${cluster.worker.id} gracefully shut down`)
        cluster.worker.kill()
}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown)
```

**Comment by alexhultman-2fa** [comment] 2020-06-13 22:07
I can trigger the same issue. I will look into this but WorkerThreads are definitely recommended over Cluster. With WorkerThreads there's a clear idea what Node.js does, while Cluster I have no idea what Node.js does and there could be bigger issues.

**Comment by hst-m** [comment] 2020-06-14 06:07
Whatever Cluster is doing it is doing it right because it does not crash with error, I think it may be doing something to prevent that error, I mean thats what its for to fork node processes to serve requests, but you could probably figure out more what is going on

**Comment by hst-m** [comment] 2020-06-14 16:00
I updated that code above to show how I use it to auto reload on file change, just update `require('uWebSockets.js')` to however you have it installed and you should be able to run the code with no issue, try updating the file while app is running to trigger graceful shutdown and reload

**Comment by alexhultman** [comment] 2020-09-08 19:50
I get all kinds of similar issues only starting a basic worker threads example and letting it close down (no server started or anything). This should be fixed and pushed harder as a main feature.

**Comment by lostrepo** [comment] 2020-10-03 23:06
@hst-m In your example you should free uWS instance inside shutdown before killing worker (cluster is a bunch of processes afaik).

In SkeLLLa`s example it can help too but as soon as any worker gets request we can't free uWS in worker, that handled it, for some time.

After ```uWS.us_listen_socket_close(socket)``` thread still handles requests (imo it shouldn't but I'm too dumb to dig into C++).
Sample log of dumb test script and reloading of ```localhost:3000``` (same happens under wrk load for all threads):
Thread dumb ID: log msg
```
703999:  /
703999:  /favicon.ico
703999:  socket close
703999:  /
703999:  /favicon.ico
...
703999:  /
703999:  /favicon.ico
```

I was able to get (uWebSockets.js 18.13.0 playing around with timeouts between ```uWS.us_listen_socket_close(socket)```, ```uWS.free()``` and thread termination):
1. ```corrupted double-linked list```
2. ```uv loop at [0x...] has open handles:...```
3. ```Segmentation fault```
4. ```Bus error```

In some cases it worked fine when delay between last handled request and ```uWS.free()``` was long enough (I guess some timeout in native land closes sockets).

[Dumb test script](https://github.com/uNetworking/uWebSockets.js/files/5322375/test.js.gz)
Navigate to or bombard ```localhost:3000``` or just wait ~21 seconds while it shuts down.
```Math.random() > 1 ? 'cleanup' : 'apptest'``` - fast auto shutdown (works) or thread socket closing on request to ```localhost:3000``` with timeout shutdown (works under condition described in previous paragraph), random was used to mix both types of threads to find workaround.

Hope it helps.

**Comment by hst-m** [comment] 2020-10-06 20:18
@lostrepo I don't know what [uWS.free](https://github.com/uNetworking/uWebSockets/blob/master/src/HttpContext.h#L352) does but looks like it gets called automatically on process exit for uWS.js:

https://github.com/uNetworking/uWebSockets.js/blob/master/src/uws.js#L28

**Comment by hst-m** [comment] 2020-10-06 21:34
looks like this issue is caused by worker threads not calling `uWS.free()` because `process.on('exit')` event only gets called for processes? adding in a `uWS.free()` in the worker before `process.exit(0)` fixes the problem

**Comment by lostrepo** [comment] 2020-10-07 10:42
@hst-m In your case timing doesn't matter since you create uWS instance for each 'forked' process (cluster stuff).

In case of worker_threads I don't understand what the flow is.
It happens if we receive connections when we close listen sockets (they still get and handle new connections after closing socket). If we call `uWS.free()` after some timeout after last connection to listen socket it sometimes works and sometimes doesn't.

**Comment by alexhultman-2fa** [comment] 2020-10-07 11:08
> In order to support Worker threads, addons need to clean up any resources they may have allocated when such a thread exists. This can be achieved through the usage of the AddEnvironmentCleanupHook() function

It looks like the add-on needs this one instead of using on close

**Comment by alexhultman** [comment] 2020-10-15 16:33
I have tested the above, and if you remove uWS.free and process.on('exit') and instead call that stuff inside AddEnvironmentCleanupHook it shuts down properly.

So I will make this change in next release and hopefully it will work better for everyone.

**Comment by alexhultman** [comment] 2020-10-15 17:10
Can everyone who had this issue try the latest binaries:

npm install uNetworking/uWebSockets.js#binaries

**Closed** 2020-10-15 17:24 UTC
Labels: bug
